var sql = require("mssql");
const vehiculos = require("../models/modelVehiculo");
const estados = require("../models/modelEstado");
const comunas = require("../models/modelComuna");

const PrimeraInscripcionSchema = {
  datosTramita: {
    primeraInscripcionID: sql.TYPES.Numeric,
    empresaID: sql.TYPES.Numeric,
    ppu: sql.TYPES.VarChar,
    estadoID: sql.TYPES.Numeric,
    estado: estados,
    numeroOperacion: sql.TYPES.VarChar,
    origen: sql.TYPES.VarChar,
    numeroFactura: sql.TYPES.VarChar,
    rutCliente: sql.TYPES.VarChar,
    vencimientoContratoLeasing: sql.TYPES.DateTime,
    rutRepresentanteLegal: sql.TYPES.VarChar,
    comunaID: sql.TYPES.Numeric,
    comuna: comunas,
    contacto: sql.TYPES.VarChar,
    telefonoContacto: sql.TYPES.VarChar,
    emailContacto: sql.TYPES.VarChar,
    numeroSolicitud: sql.TYPES.VarChar,
    estaEntregado: sql.TYPES.Bit,
    fechaSolicitudRNVM: sql.TYPES.DateTime,
    numeroValija: sql.TYPES.VarChar,
    ejecutivo: sql.TYPES.VarChar,
    sucursal: sql.TYPES.VarChar,
    fechaRecepcionBanco: sql.TYPES.DateTime,
    fechaPadron: sql.TYPES.DateTime,
    codigoDespachoCorreo: sql.TYPES.VarChar,
    fechaIngresoRNVM: sql.TYPES.DateTime,
    observacion: sql.TYPES.VarChar,
    correlativoEntrega: sql.TYPES.VarChar,
    folio: sql.TYPES.VarChar,
    fechaIngresoTAG: sql.TYPES.DateTime,
    f88: sql.TYPES.Bit,
    valorF88: sql.TYPES.Numeric,
    flCertCum5594: sql.TYPES.Bit,
    fotocopiaRutBanco: sql.TYPES.Bit,
    certificadoDS5594: sql.TYPES.Bit,
    chk1U: sql.TYPES.Bit,
    chk2U: sql.TYPES.Bit,
    chk3U: sql.TYPES.Bit,
    chk4U: sql.TYPES.Bit,
    solicitudPrimeraInscripcion: sql.TYPES.Bit,
    certificadoLeasing: sql.TYPES.Bit,
    certificadoCombustibles: sql.TYPES.Bit,
    contratoTelevia: sql.TYPES.Bit,
    convenioPAC: sql.TYPES.Bit,
    dispositivoTelevia: sql.TYPES.Bit,
    contratoLeasing: sql.TYPES.Bit,
    padron: sql.TYPES.Bit,
    pendienteContrato: sql.TYPES.Bit,
    pendienteAnotacionMeraTenencia: sql.TYPES.Bit,
    despachoExterno: sql.TYPES.Bit,
    informativoSeguro: sql.TYPES.Bit,
    fechaCreacion: sql.TYPES.DateTime,
    fechaActualizacion: sql.TYPES.DateTime,
    calidadMeroTenedorID: sql.TYPES.Numeric,
    calidadMeroTenedor: [
      {
        ID: sql.TYPES.Numeric,
        Descripcion: sql.TYPES.VarChar,
        Selected: sql.TYPES.Bit,
      },
    ],
    limitacionID: sql.TYPES.Numeric,
    monedaID: sql.TYPES.Numeric,
    notarioID: sql.TYPES.Numeric,
    naturalezaDoctoID: sql.TYPES.Numeric,
    observacionID: sql.TYPES.Numeric,
    observacionCorreoID: sql.TYPES.Numeric,
    observacionLimboID: sql.TYPES.Numeric,
    propuestaID: sql.TYPES.Numeric,
    tituloMeraTenenciaID: sql.TYPES.Numeric,
    valorCobroID: sql.TYPES.Numeric,
    clienteID: sql.TYPES.Numeric,
    usuarioID: sql.TYPES.Numeric,
    adquirenteID: sql.TYPES.Numeric,
    valorPrimeraInscripcionID: sql.TYPES.Numeric,
    valorTramitaID: sql.TYPES.Numeric,
    valorServicioTagID: sql.TYPES.Numeric,
    valorNotariaID: sql.TYPES.Numeric,
    valorDecpachoCorreoID: sql.TYPES.Numeric,
  },
  datosVehiculo: {
    vehiculoID: sql.TYPES.Numeric,
    vehiculo: vehiculos,
  },
};
module.exports = PrimeraInscripcionSchema;
