var sql = require("mssql");
const vehiculos = require("../models/modelVehiculo");
const estados = require("../models/modelEstado");
const comunas = require("../models/modelComuna");
const oficinas = require("../models/modelOficina");
const observaciones = require("../models/modelObservacion");
const cantidadPlacas = require("./modelGenerales").default;
const valoresCobro = require("../models/modelValoresCobro");
const Mensajes = require("./modelGenerales").Mensajes;

const PrimeraInscripcionSchema = {
  mensaje: null,
  datosTramita: {
    primeraInscripcionId: ((sql.TYPES.Numeric, 0), -1),
    empresaId: ((sql.TYPES.Numeric, 0), -1),
    ppu: (sql.TYPES.VarChar, ""),
    estadoId: ((sql.TYPES.Numeric, 0), -1),
    estado: estados,
    numeroOperacion: ((sql.TYPES.VarChar, ""), ""),
    origen: (sql.TYPES.VarChar, ""),
    numeroFactura: (sql.TYPES.VarChar, ""),
    rutCliente: (sql.TYPES.VarChar, ""),
    nombreRazonSocialCliente: (sql.TYPES.VarChar, ""),
    vencimientoContratoLeasing: (sql.TYPES.DateTime, null),
    representanteLegalId: (sql.TYPES.VarChar, ""),
    nombreRazonSocialRepresentanteLegal: (sql.TYPES.VarChar, ""),
    comunaId: (sql.TYPES.Numeric, 0),
    comuna: comunas,
    contacto: (sql.TYPES.VarChar, ""),
    telefonoContacto: (sql.TYPES.VarChar, ""),
    emailContacto: (sql.TYPES.VarChar, ""),

    numeroSolicitud: (sql.TYPES.VarChar, ""),
    estaEntregado: (sql.TYPES.Bit, 0),
    oficinaId: (sql.TYPES.Numeric, 0),
    oficina: oficinas,
    fechaSolicitudRnvm: (sql.TYPES.DateTime, null),
    numeroValija: (sql.TYPES.VarChar, ""),
    ejecutivo: (sql.TYPES.VarChar, ""),
    sucursal: (sql.TYPES.VarChar, ""),

    fechaRecepcionBanco: (sql.TYPES.DateTime, null),
    fechaPadron: (sql.TYPES.DateTime, null),
    codigoDespachoCorreo: (sql.TYPES.VarChar, ""),

    observacionId: (sql.TYPES.Numeric, 0),
    observacion: observaciones,
    numeroPlacas: cantidadPlacas,
    chktag: (sql.TYPES.Bit, 0),
    chkPlacas: (sql.TYPES.Bit, 0),

    numeroPlacas: (sql.TYPES.DateTime, null),
    observaciones: (sql.TYPES.VarChar, ""),
    correlativoEntrega: (sql.TYPES.VarChar, ""),
    folio: (sql.TYPES.VarChar, ""),

    valorPrimeraInscripcionId: (sql.TYPES.Numeric, 0),
    valorPrimeraInscripcion: valoresCobro,

    valorTramitaId: (sql.TYPES.Numeric, 0),
    valorTramita: valoresCobro,

    valorServicioTagId: (sql.TYPES.Numeric, 0),
    valorServicioTag: valoresCobro,

    valorNotariaId: (sql.TYPES.Numeric, 0),
    valorNotaria: valoresCobro,

    valorDespachoCorreoId: (sql.TYPES.Numeric, 0),
    valorDespachoCorreo: valoresCobro,

    fechaIngresoTag: (sql.TYPES.DateTime, null),
    f88: (sql.TYPES.Bit, 0),
    valorF88: (sql.TYPES.Numeric, 0),
    flCertCum5594: (sql.TYPES.Bit, 0),
    fotocopiaRutBanco: (sql.TYPES.Bit, 0),
    certificadoDs5594: (sql.TYPES.Bit, 0),
    chk1U: (sql.TYPES.Bit, 0),
    chk2U: (sql.TYPES.Bit, 0),
    chk3U: (sql.TYPES.Bit, 0),
    chk4U: (sql.TYPES.Bit, 0),
    solicitudPrimeraInscripcion: (sql.TYPES.Bit, 0),
    certificadoLeasing: (sql.TYPES.Bit, 0),
    certificadoCombustibles: (sql.TYPES.Bit, 0),
    contratoTelevia: (sql.TYPES.Bit, 0),
    convenioPac: (sql.TYPES.Bit, 0),
    dispositivoTelevia: (sql.TYPES.Bit, 0),
    contratoLeasing: (sql.TYPES.Bit, 0),
    padron: (sql.TYPES.Bit, 0),
    pendienteContrato: (sql.TYPES.Bit, 0),
    pendienteAnotacionMeraTenencia: (sql.TYPES.Bit, 0),
    despachoExterno: (sql.TYPES.Bit, 0),
    informativoSeguro: (sql.TYPES.Bit, 0),

    fechaCreacion: (sql.TYPES.DateTime, null),
    fechaActualizacion: (sql.TYPES.DateTime, null),
    anoProceso: (sql.TYPES.Numeric, 0),
    anoFiltro: (sql.TYPES.Numeric, 0),
    clienteId: (sql.TYPES.Numeric, 0),
    usuarioId: (sql.TYPES.Numeric, 0),
  },
  datosVehiculo: {
    vehiculoID: (sql.TYPES.Numeric, 0),
    vehiculo: vehiculos,
  },
  datosAdquirente: {
    adquirenteID: (sql.TYPES.Numeric, ""),
    rut: (sql.TYPES.VarChar, ""),
    nombreRazonSocial: (sql.TYPES.VarChar, ""),
    direccion: (sql.TYPES.Int, null),
    numero: (sql.TYPES.Int, null),
    compplemento: (sql.TYPES.Int, null),
    nroMotor: (sql.TYPES.VarChar, ""),
    nroChasis: (sql.TYPES.VarChar, ""),
    nroSerie: (sql.TYPES.VarChar, ""),
    nroVin: (sql.TYPES.VarChar, ""),
    carga: (sql.TYPES.Int, null),
    pesoBruto: (sql.TYPES.Int, ""),
    otraCarroceria: (sql.TYPES.VarChar, ""),
    nroEjes: (sql.TYPES.Int, null),
    codigoCIT: (sql.TYPES.VarChar, ""),
    nroEjesDisponibles: (sql.TYPES.Int, null),
    nroPlacas: (sql.TYPES.Int, null),
    fechaInscripcion: (sql.TYPES.DateTime, ""),
    modeloID: (sql.TYPES.Numeric, ""),
    colorID: (sql.TYPES.Numeric, ""),
    tipoVehiculoID: (sql.TYPES.Numeric, ""),
    combustibleID: (sql.TYPES.Numeric, ""),
    unidadCargaID: (sql.TYPES.Numeric, ""),
    unidadPesoID: (sql.TYPES.Numeric, ""),
    traccionID: (sql.TYPES.Numeric, ""),
    potenciaMotorID: (sql.TYPES.Numeric, ""),
    unidadPotenciaID: (sql.TYPES.Numeric, ""),
    carroceriaID: (sql.TYPES.Numeric, ""),
  },
  documentosRecibidos: [
    {
      id: (sql.TYPES.Numeric, null),
      primeraInscripcionID: (sql.TYPES.Numeric, null),
      tipoDocumentoID: (sql.TYPES.Numeric, null),
      naturalezaAdquisicion: (sql.TYPES.VarChar, null),
      nroDocumentoCausa: (sql.TYPES.VarChar, null),
      valorNeto: (sql.TYPES.Numeric, null),
      valorIVAFactura: (sql.TYPES.Numeric, null),
      valorTotalFactura: (sql.TYPES.Numeric, null),
      lugarDocumento: (sql.TYPES.VarChar, null),
      fechaDocumento: (sql.TYPES.DateTime, null),
      nombreAutorizanteEmisor: (sql.TYPES.VarChar, null),
      acreedorBeneficiarioDemandante: (sql.TYPES.VarChar, null),
      pdf: (sql.TYPES.VarChar, null),
      rutDocumento: (sql.TYPES.VarChar, null),
      tipoDocumento: (sql.TYPES.VarChar, null),
    },
  ],
};
module.exports = PrimeraInscripcionSchema;
