POST http://localhost:3000/api/validate
content-type: application/json

{
    "inputRut":"19959357-9",
    "inputPass":"12345"
}
###

POST http://localhost:3000/api/validate
content-type: application/json

{
    "inputRut":"8956722-K",
    "inputPass":"8956722."
}
###

POST http://localhost:3000/api/login
content-type: application/json

{
    "usuarioID":"1",
    "codigo":"673368"
}

###
GET http://localhost:3000/db
